#!/usr/bin/env bash
# Add a tracking domain to the SendMast server in one shot.
#
# Pre-requisites you must already have done in Cloudflare:
#   1. DNS: A record for <domain> pointing at the server IP, proxied (orange cloud).
#   2. SSL/TLS → Origin Server: edit hostnames on your existing Origin Cert
#      to include <domain> (and any wildcard you want, e.g. *.example.com).
#      Re-download cert + key and replace
#      /var/lib/sendmast/caddy-certs/origin-cert.pem (and origin-key.pem)
#      on the server. If you don't, the TLS-handshake probe at the end will
#      fail and tell you exactly that.
#
# What this script does (idempotent):
#   1. Sanity-checks the domain string and verifies DNS resolves.
#   2. Generates docker/tracking.d/<domain>.caddy locally.
#   3. scp's it to /var/lib/sendmast/caddy-tracking.d/ on the server.
#   4. `docker compose exec caddy caddy reload`.
#   5. Probes https://<domain>/t/o/_probe.gif to confirm Caddy is serving
#      and the Origin Cert SAN covers the new host.
#
# What this script does NOT do:
#   - Add the domain to the `tracking_domains` Postgres table. The pool
#     selector in worker-sender only consults rows with status='active',
#     and we deliberately don't bake API auth into a shell script.
#     Open https://app.sendmast.com/admin/tracking-domains and click
#     「添加并启用」 once the script finishes — 30s later the new host
#     enters rotation.
#
# Usage:
#   scripts/add-tracking-domain.sh <domain>
#   scripts/add-tracking-domain.sh <domain> <server-host> <ssh-user>
#
# Examples:
#   scripts/add-tracking-domain.sh t1.mailtrk.cn
#   scripts/add-tracking-domain.sh t1.mailtrk.cn 74.208.77.128 root
#
# Env overrides (rarely needed):
#   DATA_ROOT     server-side bind-mount root, default /var/lib/sendmast
#   COMPOSE_FILE  compose file path on server, default docker/docker-compose.prod.yml
#   ENV_FILE      env file path on server, default .env.production

set -euo pipefail

# ─── Args ───────────────────────────────────────────────────────────────────
DOMAIN="${1:-}"
SERVER="${2:-74.208.77.128}"
SSH_USER="${3:-root}"

if [[ -z "$DOMAIN" ]]; then
  cat <<EOF >&2
usage: $(basename "$0") <domain> [server-host] [ssh-user]

example:
  $(basename "$0") t1.mailtrk.cn
EOF
  exit 2
fi

# lowercase — schema and Caddy both treat as case-insensitive. tr-based form
# instead of bash 4's ${var,,} so this works on macOS's stock bash 3.2.
DOMAIN="$(printf '%s' "$DOMAIN" | tr '[:upper:]' '[:lower:]')"

# RFC-ish hostname check. Allows multi-level subdomains; rejects schemes/paths.
if [[ ! "$DOMAIN" =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$ ]]; then
  echo "✗ '$DOMAIN' doesn't look like a bare domain (no protocol/path)." >&2
  exit 1
fi

DATA_ROOT="${DATA_ROOT:-/var/lib/sendmast}"
COMPOSE_FILE="${COMPOSE_FILE:-docker/docker-compose.prod.yml}"
ENV_FILE="${ENV_FILE:-.env.production}"
REMOTE_REPO="/root/sendmast"
REMOTE_TRACKING_DIR="$DATA_ROOT/caddy-tracking.d"
REMOTE_FILE="$REMOTE_TRACKING_DIR/$DOMAIN.caddy"

SSH_TARGET="$SSH_USER@$SERVER"
SSH_OPTS=(-o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new)

# ─── 1. DNS sanity ──────────────────────────────────────────────────────────
echo "▶ Checking DNS for $DOMAIN ..."
if ! command -v dig >/dev/null 2>&1; then
  echo "  (dig not installed — skipping DNS check)"
else
  RESOLVED=$(dig +short +time=3 +tries=2 "$DOMAIN" A | grep -E '^[0-9.]+$' | head -1 || true)
  if [[ -z "$RESOLVED" ]]; then
    echo "✗ $DOMAIN has no A record yet. Add the DNS in Cloudflare first." >&2
    exit 1
  fi
  echo "  resolves to $RESOLVED"
fi

# ─── 2. Generate Caddy snippet ──────────────────────────────────────────────
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
LOCAL_FILE="$TMP_DIR/$DOMAIN.caddy"

# Mirrors the snippet generator in
# apps/web/src/pages/admin/AdminTrackingDomainsPage.tsx — keep them in sync
# if you tweak the layout. (We can't share a literal because one runs in
# the browser and one runs in bash; the redundancy is intentional and small.)
cat > "$LOCAL_FILE" <<EOF
# Tracking domain: $DOMAIN
# Generated by scripts/add-tracking-domain.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ').
# Drop into $REMOTE_TRACKING_DIR/ on the server, then \`caddy reload\`.
$DOMAIN {
	tls /etc/caddy/certs/origin-cert.pem /etc/caddy/certs/origin-key.pem
	encode gzip zstd

	handle /t/* {
		reverse_proxy api:4000
	}

	handle {
		respond "Not Found" 404
	}

	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options nosniff
	}

	log {
		output stdout
		format console
	}
}
EOF

echo "▶ Generated $LOCAL_FILE"

# ─── 3. SSH connectivity ────────────────────────────────────────────────────
echo "▶ Connecting to $SSH_TARGET ..."
if ! ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'echo ok' >/dev/null; then
  echo "✗ SSH to $SSH_TARGET failed. Check key / host / network." >&2
  exit 1
fi

# ─── 4. Ensure remote dir, scp, then reload ────────────────────────────────
echo "▶ Uploading to $SSH_TARGET:$REMOTE_FILE ..."
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "mkdir -p '$REMOTE_TRACKING_DIR'"
scp "${SSH_OPTS[@]}" "$LOCAL_FILE" "$SSH_TARGET:$REMOTE_FILE" >/dev/null

echo "▶ Reloading Caddy ..."
# Validate first so a syntax error in the snippet aborts before reload.
# `caddy fmt` would also work but `caddy validate --adapter caddyfile` is
# stricter (catches references to nonexistent files).
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" \
  "cd '$REMOTE_REPO' && \
   docker compose --env-file '$ENV_FILE' -f '$COMPOSE_FILE' \
   exec -T caddy caddy validate --config /etc/caddy/Caddyfile" \
  >/dev/null

ssh "${SSH_OPTS[@]}" "$SSH_TARGET" \
  "cd '$REMOTE_REPO' && \
   docker compose --env-file '$ENV_FILE' -f '$COMPOSE_FILE' \
   exec -T caddy caddy reload --config /etc/caddy/Caddyfile" \
  >/dev/null

echo "  reload OK"

# ─── 5. TLS handshake probe ─────────────────────────────────────────────────
# Sleep briefly so DNS-cache + Caddy worker swap can settle.
sleep 2

echo "▶ Probing https://$DOMAIN/t/o/_probe.gif ..."
HTTP_STATUS=$(curl -sS -o /dev/null -w '%{http_code}' \
  --max-time 10 \
  "https://$DOMAIN/t/o/_probe.gif" 2>&1 || true)

# Expected response: 400 / 404 (token is bogus by design) — what matters is
# the TLS handshake succeeded and we got an HTTP response at all. A
# connect/cert error shows up here as 000 + a stderr blurb from curl.
case "$HTTP_STATUS" in
  4??)
    echo "✓ Caddy is serving $DOMAIN (TLS OK, HTTP $HTTP_STATUS — bogus token expected)."
    ;;
  2??)
    echo "✓ Caddy responded HTTP $HTTP_STATUS (unusual but fine — TLS works)."
    ;;
  000)
    echo "✗ TLS / connect failed. Likely causes:" >&2
    echo "   - Origin Cert SAN doesn't include $DOMAIN (re-issue + re-upload cert files)." >&2
    echo "   - DNS hasn't propagated yet (wait a minute, retry)." >&2
    echo "   - Cloudflare proxy is off / misrouted." >&2
    exit 1
    ;;
  *)
    echo "⚠ Unexpected HTTP $HTTP_STATUS. Inspect manually:" >&2
    echo "   curl -v https://$DOMAIN/t/o/_probe.gif" >&2
    exit 1
    ;;
esac

# ─── 6. Done — point user at admin UI ──────────────────────────────────────
cat <<EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✓ $DOMAIN is reachable. One step left:

  Open https://app.sendmast.com/admin/tracking-domains
  → click 「添加域名」, fill in:    $DOMAIN
  → click 「添加并启用」

worker-sender will pick it up within ~30 seconds (pool cache TTL) and start
hashing recipient ids onto $DOMAIN alongside any other active domains.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
